@startuml
' https://plantuml.com/component-diagram

package "Console" {
  [AppReversiConsole]
  [Commands]
  [ReversiView]
  [Input]
}

package "Domain" {
  [Game]
  [Reversi]
  [Clash]
}

package "Storage" {
  [Storage ]
  [Serializer]
  [TextFileStorage]
  [GameSerializer]
}

package "App" {
  [Main]
}

[Main] --> [AppReversiConsole]

[AppReversiConsole] ..> [Input]
[AppReversiConsole] ..> [Commands]
[AppReversiConsole] --> [TextFileStorage]
[AppReversiConsole] --> [GameSerializer]
[ReversiView] --> [Reversi]

[Commands] --> [Reversi]
[Commands] --> [Clash]
[Reversi] ..> [Game]
[Clash] ..> [Game]

[Clash] --> [Storage ]
[Clash] ..> [Reversi]

[TextFileStorage] ..> [Storage ]
[GameSerializer] ..> [Serializer]
[TextFileStorage] ..> [Serializer]
[GameSerializer] --> [Reversi]

@enduml