@startuml
' https://plantuml.com/class-diagram
hide empty members
package console {
  object AppReversiConsole
  class Command
  interface CommandContext
  class CommandContextEmpty
  class GameInProgress
  class CommandException
  class InvalidParameters
  class Unknown
  class IllegalContext
  class ReversiView
  class Input
  class LineCommand

  CommandContext <|-- CommandContextEmpty
  CommandContext <|-- GameInProgress
  CommandException <|-- InvalidParameters
  CommandException <|-- Unknown
  CommandException <|-- IllegalContext
}

package model {
  interface Game
  class Reversi
  class Clash
  class Coordinate
  enum Direction
  class Name
  enum PiecesColor

  abstract class GameState
  class Win
  class Draw
  class Run
  class Pass

  Game <|-- Reversi
  Game <|-- Clash
  GameState <|-- Win
  GameState <|-- Draw
  GameState <|-- Run
  GameState <|-- Pass
}

package storage {
  interface Storage
  interface Serializer
  class TextFileStorage
  class GameSerializer

  Storage <|-- TextFileStorage
  Serializer <|-- GameSerializer
}

console.GameInProgress --> model.Game
console.Command --> console.CommandContext
console.ReversiView --> model.Reversi
console.Input --> console.LineCommand

model.Clash --> storage.Storage
storage.GameSerializer --> model.Reversi
storage.TextFileStorage --> storage.Serializer
@enduml